<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [52]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# Note: The result provided in your example 2 is incorrect

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    matrixARowSize = len(A)
    if 0 == matrixARowSize:
        return
    
    matrixBRowSize = len(B)
    if 0 == matrixBRowSize:
        return
    
    matrixAColSize = len(A[0])
    if 0 == matrixAColSize:
        return
    
    matrixBColSize = len(B[0])
    if 0 == matrixBColSize:
        return
    
    if matrixAColSize != matrixBRowSize:
        print("Not Possible\n")
        return
    
    productList = list()
    for i in range(matrixARowSize):
        elementList = list()
        for j in range(matrixBColSize):
            product = 0
            for k in range(matrixAColSize):
                product += A[i][k] * B[k][j]
            elementList.append(product)
        productList.append(elementList)
    
    return productList
    
A = [[1, 2], [3, 4], [5, 6]]
B = [[1, 2, 3], [4, 5, 6]]
product = matrix_mul(A, B)
print(product)

[[9, 12, 15], [19, 26, 33], [29, 40, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [58]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A, probabilityArr):
    randomNumber = uniform(0, 1)
    probabilityArr.append(randomNumber)
    probabilityArr.sort()
    
    index = probabilityArr.index(randomNumber)
    probabilityArr.remove(randomNumber)
    
    return A[index]

def sampling_based_on_magnitued(A):
    sumOfArray = sum(A)
    
    A.sort()

    probabilityArr = list()
    percentList = list()
    
    for i in range(len(A)):
        percent = (A[i] / sumOfArray)
        percentList.append(percent)
        probabilityArr.append(sum(percentList))
    
    for i in range(1, 100):
        number = pick_a_number_from_list(A, probabilityArr)
        print(number)

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
sampling_based_on_magnitued(A)

100
100
100
79
100
79
100
79
100
79
100
100
100
13
100
13
79
100
13
45
79
27
28
100
45
79
100
27
79
45
79
13
100
28
100
100
27
79
27
45
79
100
28
45
27
100
79
27
100
28
28
79
10
100
6
100
100
100
27
100
79
79
79
100
100
45
79
100
100
79
79
28
79
79
100
100
27
100
45
27
100
79
100
79
79
100
79
13
100
100
13
79
100
100
45
79
28
28
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [17]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    address = re.findall('\d', String)
    numericString = ''.join(address)
    return re.sub('\d', '#', numericString)

String = str(input("Enter the string to modify : \n"));
modifiedStr = replace_digits(String);
print(modifiedStr);

Enter the string to modify : 
#2a$#b%c%561# 
####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [1]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

def calculate_percentile(sortedMarks):
    minMarks = min(sortedMarks)
    maxMarks = max(sortedMarks)
    
    difference = maxMarks - minMarks
    
    return difference * 0.25, difference * 0.75

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    if (len(students) != len(marks)):
        return NULL
    
    stuMarksDict = dict()
    for i in range(len(students)):
        stuMarksDict[marks[i]] = students[i]
    
    sortedMarks = sorted(marks, reverse = True)
    
    top_5_students = dict()
    for i in range(5):
        top_5_students[stuMarksDict.get(sortedMarks[i])] = sortedMarks[i]
    
    # write code for computing top least 5 students
    sortedMarks.reverse()
    least_5_students = dict()
    for i in range(5):
        least_5_students[stuMarksDict.get(sortedMarks[i])] = sortedMarks[i]
    
    # write code for computing top least 5 students
    students_within_25_and_75 = dict()
    
    percentile25, percentile75 = calculate_percentile(sortedMarks)
    
    for i in range(len(sortedMarks)):
        if sortedMarks[i] > percentile25 and sortedMarks[i] < percentile75:
            students_within_25_and_75[stuMarksDict.get(sortedMarks[i])] = sortedMarks[i]
        
    return top_5_students, least_5_students, students_within_25_and_75

students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80] 
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)

print("Top 5 students based on their marks : \n")
for pairs in top_5_students.items():
    top5Students = list(pairs)
    print("{0} {1}".format(top5Students[0], top5Students[1]))
    
print("\nBottom 5 students based on their marks : \n")
for pairs in least_5_students.items():
    bottom5Students = list(pairs)
    print("{0} {1}".format(bottom5Students[0], bottom5Students[1]))
    
print("\nMiddle students with their percentile between 25 and 75 : \n")
for pairs in students_within_25_and_75.items():
    mid5Students = list(pairs)
    print("{0} {1}".format(mid5Students[0], mid5Students[1]))

Top 5 students based on their marks : 

student8 98
student10 80
student2 78
student5 48
student7 47

Bottom 5 students based on their marks : 

student3 12
student4 14
student9 35
student6 43
student1 45

Middle students with their percentile between 25 and 75 : 

student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [9]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    referenceLst = list(P);
    
    closestPointStore = dict();
    finalList = []
    
    for i in range(len(S)):
        tupleLst = list(S[i])        
        numerator = (tupleLst[0] * referenceLst[0]) + (tupleLst[1] * referenceLst[1])
        denominator = (math.sqrt(tupleLst[0] ** 2 + tupleLst[1] ** 2)) * (math.sqrt(referenceLst[0] ** 2 + referenceLst[1] ** 2))
        result = numerator / denominator
        distance = math.acos(result)
        
        closestPointStore[distance] = i
    
    keysList = list(closestPointStore.keys())
    keysList.sort()
    
    for i in range(5):
        index = closestPointStore.get(keysList[i])
        
        if index == None:
            continue;
        
        finalList.append(S[index])
    
    return finalList

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [97]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

def check_for_point_presence(color, line):
    pointInPosSide = False
    #coefficient = re.findall(r'-?\d*\.\d+|-?\d+', line)
    coefficient = re.findall(r'[\d\.\-\+]+', line)
    colorPositionList = []
    for i in range(len(color)):
        pointPosition = 0
        colorList = list(color[i])
        pointPosition += (float(coefficient[0]) * colorList[0]) + (float(coefficient[1]) * colorList[1]) + float(coefficient[2])
        colorPositionList.append(pointPosition)
    maxColorValue = max(colorPositionList)
    minColorValue = min(colorPositionList)
    
    if maxColorValue > 0 and minColorValue >= 0:
        pointInPosSide = True
    elif maxColorValue >= 0 and minColorValue < 0:
        return "No"
    else:
        pointInPosSide = False 
    
    return pointInPosSide

# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    if len(red) != len(blue):
        return
    
    redPtPosition = check_for_point_presence(red, line)
    if isinstance(redPtPosition, str):
        return redPtPosition
    
    bluePtPosition = check_for_point_presence(blue, line)
    if isinstance(bluePtPosition, str):
        return bluePtPosition
    
    if bluePtPosition != redPtPosition:
        return "Yes"
    
    return "No"
    
Red= [(1, 1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [88]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure

def curve_smoothing(string):
    newString = string.replace('_', '0')
    strList = newString.split(',')
       
    if 1 == len(strList) - strList.count('0'):
        for i in range(len(strList)):
            if '0' == strList[i]:
                continue
            else:
                result = int(strList[i]) / len(strList)
                break
        
        for i in range(len(strList)):
            strList[i] = result
        return strList
    
    left = 0
    right = 0

    for i in range(1, len(strList)):
        if i == len(strList) - 1:
            result = (int(strList[left]) + int(strList[i])) / (i - left + 1)
            for j in range(left, i + 1):
                strList[j] = result
            continue
            
        elif '0' == strList[i]:
            continue
        else:
            right = i
        result = (int(strList[left]) + int(strList[right])) / (right - left + 1)
        for j in range(left, i + 1):
            strList[j] = result
        left = right
    return strList

S = "_,_,_,24"
smoothed_values = curve_smoothing(S)
print(smoothed_values)

S = "40,_,_,_,60"
smoothed_values = curve_smoothing(S)
print(smoothed_values)

S = "80,_,_,_,_"
smoothed_values = curve_smoothing(S)
print(smoothed_values)

S = "_,_,30,_,_,_,50,_,_"
smoothed_values = curve_smoothing(S)
print(smoothed_values)

[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [42]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    condProbDict = dict()
    uniqueValues = list()
    for condProb in A:
        condProbList = condProbDict.get(condProb[1])
        uniqueValues.append(condProb[0])
        
        if None == condProbList:
            FList = list()
            FList.append(condProb[0])
            condProbDict[condProb[1]] = FList
        else:
            condProbList.append(condProb[0])
            
    uniqueSet = list(set(uniqueValues))
    
    keysList = list(condProbDict.keys())
    
    for keys in keysList:
        valueList = condProbDict.get(keys)
        
        for i in range(len(uniqueSet)):
            try:
                index = valueList.index(uniqueSet[i])
                probability = 1
            except:
                probability = 0
            print("P(F={0}|S=={1})={2}/{3}".format(uniqueSet[i], keys, probability, len(valueList)))
        
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

P(F=F5|S==S1)=1/4
P(F=F3|S==S1)=0/4
P(F=F4|S==S1)=1/4
P(F=F1|S==S1)=1/4
P(F=F2|S==S1)=1/4
P(F=F5|S==S2)=0/3
P(F=F3|S==S2)=1/3
P(F=F4|S==S2)=0/3
P(F=F1|S==S2)=1/3
P(F=F2|S==S2)=1/3
P(F=F5|S==S3)=0/3
P(F=F3|S==S3)=1/3
P(F=F4|S==S3)=1/3
P(F=F1|S==S3)=0/3
P(F=F2|S==S3)=1/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [28]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    S1List = S1.split()
    S2List = S2.split()
    
    commonWordsCount = 0
    S1Result = list()
    S2Result = list()
    
    # Checking which list is having the least members as that becomes the members of that list will become
    # the one to get checked with the list with more members
    if len(S1List) < len(S2List):
        referenceList = S2List
        compareList = S1List
    else:
        referenceList = S1List
        compareList = S2List
    
    for i in range(len(compareList)):
        try:
            index = referenceList.index(compareList[i])
            commonWordsCount += 1
        except:
            S1Result.append(compareList[i])
            S2Result.append(referenceList[i])
    
    # Consider S1 = "the first column F will contain only 5 uniques"
    # Consider S2 = "the second column S will contain only 3 uniques values"
    # Here the word "values" is an extra word and hence can never be common between both the string.
    # Hence we can blindly add this word to the list
    for i in range(len(compareList), len(referenceList)):
        S2Result.append(referenceList[i])
    
    return commonWordsCount, S1Result, S2Result

S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

print("\n")

S1 = "the first column S will contain only 3 uniques values"
S2 = "the first column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

print("\n")

S1 = "the second"
S2 = "the first column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['second', 'S', '3']
['first', 'F', '5']


10
[]
[]


1
['second']
['first', 'column', 'S', 'will', 'contain', 'only', '3', 'uniques', 'values']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [32]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def compute_log_loss(A):
    product = 0
    for logLossList in A:
        product += (logLossList[0] * math.log(logLossList[1], 10)) + ((1 - logLossList[0]) * math.log(1 - logLossList[1], 10))
    
    loss = (product * -1) / len(A)
        
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
